### ISSUE TITLE
License Permission

### ISSUE THREAD

**Issue by gockxml** [LSTM-Kirigaya/typora-haru-theme#10]
Hi there, your theme is very beautiful, I love it so much. I'm working on a Markdown plugin for OneNote, which will support loading Typora themes. And I want to embed your theme as one of the default choices, with a little modifications on the style and keeping all the name/link/author information. Before doing that, I have to ask about the license permission. How do you feel about it?

**Comment by LSTM-Kirigaya** [comment]
Hey gays, just use the theme as you want, have fun!

**Comment by gockxml** [comment]
Got it, thanks very much!
